title: DissentVerse
baseurl: "/dissentverse"
url: "https://dissentverse.github.io"
future: true

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: "admin"
    values:
      sitemap: false
